<a href="https://colab.research.google.com/github/gurjan/pyda/blob/main/math_for_data_analysis/hw2_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Уровень 0:
###Задание 1
- Создайте матрицу 3 на 3, заполненную числами от 1 до 9
- Прибавьте к ней матрицу с единицами на диагонале
- Умножьте полученную матрицу на вектор (1, 2, 3)
- Вычислить транспонированную матрицу A^T от полученной в результате прибавления матрицы
-Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [ ]:
# Создайте матрицу 3 на 3, заполненную числами от 1 до 9
A1= np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
# A1 = np.random.randint(1,9, size=(3, 3)) # using random allocation
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Прибавьте к ней матрицу с единицами на диагонале
A2 = np.eye(3)
A3 = A1+A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [ ]:
# Умножьте полученную матрицу на вектор (1, 2, 3)
A4 = A3@np.array([1,2,3])
A4

array([15., 34., 53.])

In [ ]:
# Вычислить транспонированную матрицу A^T от полученной в результате прибавления матрицы
A4 = np.transpose(A3)
A4

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [ ]:
# Посчитайте обратную матрицу к полученной в результате прибавления матрице
A5 = np.linalg.inv(A3)
A5

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [ ]:
A3@A5

array([[ 1.00000000e+00, -3.33066907e-16,  6.66133815e-16],
       [-5.32907052e-15,  1.00000000e+00,  1.33226763e-15],
       [-1.77635684e-15, -1.11022302e-15,  1.00000000e+00]])

##Уровень 1:
###Задание 2
Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
- print(m)

In [ ]:
m = np.array([[2, 2], [1, 3]])

In [ ]:
# собственные значения
np.linalg.eigvals(m)
# m1 = np.linalg.eig(m)
# m1[0]

array([1., 4.])

In [ ]:
# собственные вектора
m1 = np.linalg.eig(m)
m2 = m1[1]
m3 = np.transpose(m2)
print("1st:", m3[0]/0.4472136, "\n2nd:", m3[1]/-0.70710678)

1st: [-1.99999998  0.99999999] 
2nd: [1. 1.]


## Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [ ]:
B1= np.array([[2, 3, 6], [1, 1, 4],[1,2,1]])
B1

array([[2, 3, 6],
       [1, 1, 4],
       [1, 2, 1]])

In [ ]:
np.linalg.det(B1)

1.0

In [ ]:
np.linalg.matrix_rank(B1)

3